import { Inter } from 'next/font/google'
import { Analytics } from '@vercel/analytics/react';

import './globals.css'
import TopNavBar from '@/components/TopNavBar';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TopNavBar/>
        <div className="w-full flex justify-center">
          {children}
        </div>
        <Analytics/>
      </body>
    </html>
  )
}
